# These are supported funding model platforms

# github: [aronanda] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: aronanda
open_collective: aronanda
ko_fi: aronanda # Replace with a single Ko-fi username
tidelift: "npm/aronanda"
custom: AaronKrieshok.com # Replace with a single custom sponsorship URL
